# Generated by Django 3.2.5 on 2021-07-29 20:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210730_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9ced3050-8377-410a-ae05-22183327e212'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('45fcfac7-3903-442f-8bf2-faaa5865a3e6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b261f839-6624-4f6c-bc6d-30fb244738f8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
